# Generated by Django 5.0.6 on 2025-07-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="location",
        ),
        migrations.AddField(
            model_name="event",
            name="geolocation",
            field=models.JSONField(default=dict),
        ),
    ]
