# Generated by Django 5.0.6 on 2025-07-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0002_remove_event_location_event_geolocation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="geolocation",
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
