# Generated by Django 5.0.6 on 2025-07-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0003_remove_event_geolocation_event_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="duration_hours",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
