# Generated by Django 5.0.6 on 2025-07-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0004_event_duration_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="thumbnail",
            field=models.ImageField(
                blank=True, max_length=600, null=True, upload_to="thumbs"
            ),
        ),
    ]
