# Generated by Django 5.0.6 on 2025-08-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0006_devicetoken_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetoken",
            name="timezone",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
