# Generated by Django 5.0.6 on 2025-10-10 15:03

import django.db.models.deletion
import django.utils.timezone
import mobicrowd.models.submisson
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0007_devicetoken_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("image", "Image problem"), ("bug", "Bug report")],
                        default="image",
                        max_length=16,
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=600,
                        null=True,
                        upload_to=mobicrowd.models.submisson.report_upload_to,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="mobicrowd.submission",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="mobicrowd.worker",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
