# Generated by Django 5.0.6 on 2025-10-28 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0008_submissionreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(max_length=600, upload_to="videos")),
                ("duration", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(default=dict)),
                ("resolution", models.CharField(blank=True, max_length=255, null=True)),
                ("codec", models.CharField(blank=True, max_length=255, null=True)),
                ("frame_rate", models.FloatField(blank=True, null=True)),
                ("size", models.FloatField(blank=True, null=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, max_length=600, null=True, upload_to="thumbnails"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="submission",
            name="video",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mobicrowd.video",
            ),
        ),
    ]
