# Generated by Django 5.0.6 on 2025-10-28 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0009_video_submission_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="submission",
        ),
        migrations.AddField(
            model_name="submission",
            name="photo",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mobicrowd.photo",
            ),
        ),
    ]
