# Generated by Django 5.0.6 on 2025-10-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0010_remove_photo_submission_submission_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="codec",
        ),
        migrations.RemoveField(
            model_name="video",
            name="frame_rate",
        ),
        migrations.RemoveField(
            model_name="video",
            name="resolution",
        ),
        migrations.AddField(
            model_name="event",
            name="media_types",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
