# Generated by Django 5.0.6 on 2025-11-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0011_remove_video_codec_remove_video_frame_rate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="cost",
        ),
        migrations.AddField(
            model_name="event",
            name="max_videos_per_worker",
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="numberOfVideos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="photo_reward",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="video_reward",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="max_photos_per_worker",
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="numberOfPhotos",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
