# Generated by Django 5.0.6 on 2025-11-09 17:26

import mobicrowd.models.submisson
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0012_remove_event_cost_event_max_videos_per_worker_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submissionreport",
            name="image",
        ),
        migrations.AddField(
            model_name="submissionreport",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=600,
                null=True,
                upload_to=mobicrowd.models.submisson.report_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="submissionreport",
            name="type",
            field=models.CharField(
                choices=[("media", "Media problem"), ("bug", "Bug report")],
                default="media",
                max_length=16,
            ),
        ),
    ]
