# Generated by Django 5.0.6 on 2025-11-10 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mobicrowd",
            "0013_remove_submissionreport_image_submissionreport_file_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submissionreport",
            name="submission",
        ),
        migrations.AddField(
            model_name="submissionreport",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="mobicrowd.event",
            ),
        ),
        migrations.AlterField(
            model_name="submissionreport",
            name="type",
            field=models.CharField(
                choices=[("photo", "photo"), ("video", "video")],
                default="photo",
                max_length=16,
            ),
        ),
    ]
