# Generated by Django 5.0.6 on 2025-11-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0014_remove_submissionreport_submission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="worker_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
