# Generated by Django 5.0.6 on 2025-11-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0015_submission_worker_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="worker_message_read",
            field=models.BooleanField(default=False),
        ),
    ]
