# Generated by Django 5.0.6 on 2025-11-11 10:58

import mobicrowd.models.submisson
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0016_submission_worker_message_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionreport",
            name="thumbnail",
            field=models.FileField(
                blank=True,
                max_length=600,
                null=True,
                upload_to=mobicrowd.models.submisson.report_upload_to_thumb,
            ),
        ),
    ]
