# Generated by Django 5.0.6 on 2026-01-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0018_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="location",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
