# Generated by Django 5.0.6 on 2026-01-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0019_alter_submission_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="caption",
            field=models.TextField(blank=True),
        ),
    ]
