# Generated by Django 5.0.6 on 2026-02-18 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0020_video_caption"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="keywords",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
