# Generated by Django 5.0.6 on 2026-02-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0021_event_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="keywords",
            field=models.TextField(blank=True, null=True),
        ),
    ]
