# Generated by Django 5.0.6 on 2026-03-02 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0022_alter_event_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetoken",
            name="device_uid",
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
