# Generated by Django 5.0.6 on 2026-03-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0023_devicetoken_device_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetoken",
            name="kind",
            field=models.CharField(
                choices=[("APP", "App"), ("DASHBOARD", "Dashboard")],
                default="APP",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="session_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="session_last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="session_sid",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="device_uid",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="token",
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
