# Generated by Django 5.0.6 on 2026-03-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0024_devicetoken_kind_devicetoken_session_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicetoken",
            name="kind",
            field=models.CharField(
                choices=[("APP", "App"), ("DASHBOARD", "Dashboard")], max_length=16
            ),
        ),
    ]
