# Generated by Django 5.0.6 on 2026-03-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0026_user_is_representative_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionreport",
            name="submission_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
