# Generated by Django 5.0.6 on 2026-03-09 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0027_submissionreport_submission_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="keywords",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
