# Generated by Django 5.0.6 on 2026-03-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0028_alter_event_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="keywords",
            field=models.TextField(blank=True, default=""),
        ),
    ]
