# Generated by Django 5.0.6 on 2026-03-09 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0029_alter_event_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionreport",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="mobicrowd.submission",
            ),
        ),
        migrations.AddConstraint(
            model_name="submissionreport",
            constraint=models.UniqueConstraint(
                fields=("worker", "submission"),
                name="uniq_report_per_worker_submission",
            ),
        ),
    ]
