# Generated by Django 5.0.6 on 2026-03-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0030_submissionreport_submission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="extracted_text",
            field=models.TextField(blank=True),
        ),
    ]
