# Generated by Django 5.0.6 on 2026-05-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0041_workshop"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="word_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
