# Generated by Django 5.0.6 on 2026-05-20 12:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0042_event_word_limit"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkshopMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")], max_length=10
                    ),
                ),
                ("original_event_id", models.IntegerField(blank=True, null=True)),
                ("original_submission_id", models.IntegerField(blank=True, null=True)),
                ("original_photo_id", models.IntegerField(blank=True, null=True)),
                ("original_video_id", models.IntegerField(blank=True, null=True)),
                (
                    "action_status",
                    models.CharField(
                        choices=[
                            ("selected", "Selected"),
                            ("processed", "Processed"),
                            ("removed", "Removed"),
                        ],
                        default="selected",
                        max_length=20,
                    ),
                ),
                ("action_payload", models.JSONField(blank=True, default=dict)),
                ("added_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workshop_media_items",
                        to="mobicrowd.event",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workshop_media_items",
                        to="mobicrowd.photo",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workshop_media_items",
                        to="mobicrowd.submission",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workshop_media_items",
                        to="mobicrowd.video",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_items",
                        to="mobicrowd.workshop",
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="workshopmedia",
            constraint=models.UniqueConstraint(
                fields=("workshop", "submission", "media_type"),
                name="uniq_workshop_submission_media_type",
            ),
        ),
    ]
