# Generated by Django 5.0.6 on 2026-05-21 14:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0043_workshopmedia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkshopActionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_uid", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("action_key", models.CharField(db_index=True, max_length=64)),
                (
                    "media_kind",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("video", "Video"),
                            ("mixed", "Mixed"),
                            ("text", "Text"),
                        ],
                        default="photo",
                        max_length=16,
                    ),
                ),
                (
                    "media_name",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="success",
                        max_length=16,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("result_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workshop_action_results",
                        to="mobicrowd.requester",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_results",
                        to="mobicrowd.workshop",
                    ),
                ),
                (
                    "workshop_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_results",
                        to="mobicrowd.workshopmedia",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workshop", "action_key"],
                        name="mobicrowd_w_worksho_750ae7_idx",
                    ),
                    models.Index(
                        fields=["workshop", "run_uid"],
                        name="mobicrowd_w_worksho_074c0d_idx",
                    ),
                    models.Index(
                        fields=["workshop_media", "action_key"],
                        name="mobicrowd_w_worksho_b794eb_idx",
                    ),
                ],
            },
        ),
    ]
