# Generated by Django 5.0.6 on 2026-05-21 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0044_workshopactionresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshopactionresult",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workshop_action_results",
                to="mobicrowd.event",
            ),
        ),
        migrations.AddField(
            model_name="workshopactionresult",
            name="label_colors",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="workshopactionresult",
            name="output_media_kind",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="workshopactionresult",
            name="output_media_mime_type",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="workshopactionresult",
            name="output_media_size_bytes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workshopactionresult",
            name="output_media_storage_key",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="workshopactionresult",
            name="output_media_url",
            field=models.URLField(blank=True, default="", max_length=2048),
        ),
        migrations.AddIndex(
            model_name="workshopactionresult",
            index=models.Index(
                fields=["workshop", "event", "action_key"],
                name="mobicrowd_w_worksho_74e513_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workshopactionresult",
            index=models.Index(
                fields=["workshop", "event", "run_uid"],
                name="mobicrowd_w_worksho_3b2a5a_idx",
            ),
        ),
    ]
