# Generated by Django 5.0.6 on 2026-05-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0045_workshopactionresult_event_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="word_limit",
        ),
        migrations.AddField(
            model_name="event",
            name="max_texts_per_worker",
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="numberOfTexts",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="text_reward",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
