# Generated by Django 5.0.6 on 2026-06-16 15:21

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mobicrowd",
            "0046_remove_event_word_limit_event_max_texts_per_worker_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginTakeoverChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "challenge_id",
                    models.CharField(
                        default=secrets.token_urlsafe, max_length=96, unique=True
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("EMAIL_OTP", "Email OTP"),
                            ("ACTIVE_SESSION", "Active Session Approval"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("APP", "App"), ("DASHBOARD", "Dashboard")],
                        max_length=16,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("web", "Web"),
                        ],
                        max_length=16,
                    ),
                ),
                ("incoming_device_uid", models.CharField(max_length=128)),
                (
                    "incoming_device_label",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("otp_hash", models.CharField(blank=True, default="", max_length=128)),
                ("otp_attempts", models.PositiveSmallIntegerField(default=0)),
                ("status", models.CharField(default="PENDING", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by_device_uid",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "status", "created_at"],
                        name="mobicrowd_l_user_id_c51424_idx",
                    ),
                    models.Index(
                        fields=["challenge_id"], name="mobicrowd_l_challen_38bb1f_idx"
                    ),
                    models.Index(
                        fields=["incoming_device_uid"],
                        name="mobicrowd_l_incomin_f39ab8_idx",
                    ),
                ],
            },
        ),
    ]
