# Generated by Django 5.0.6 on 2026-08-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0047_logintakeoverchallenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventworker",
            name="approved_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="licence_duration",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="licence_expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                blank=True, max_length=600, null=True, upload_to="users-profile-photos/"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="licence_contributor",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="organization",
            name="licence_requester",
            field=models.IntegerField(default=0),
        ),
    ]
