# Generated by Django 5.0.6 on 2026-09-02 15:42

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0048_eventworker_approved_at_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="unique_organization_name_case_insensitive",
            ),
        ),
    ]
