# Generated by Django 5.0.6 on 2026-09-08 12:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0049_organization_unique_organization_name_case_insensitive"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="flow_artifact_digest",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="flow_artifact_path",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="flow_finalized_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="flow_nonce",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="submission",
            name="flow_stage",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("decoding", "Decoding"),
                    ("decoded", "Decoded"),
                    ("validating", "Validating"),
                    ("validated", "Validated"),
                    ("finalizing", "Finalizing"),
                    ("finalized", "Finalized"),
                    ("refused", "Refused"),
                ],
                db_index=True,
                default="created",
                editable=False,
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="flow_validated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
