# Generated by Django 5.0.6 on 2026-09-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobicrowd", "0050_submission_flow_artifact_digest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="licence_starting_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="renewable",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="organization",
            name="licence_contributor",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="organization",
            name="licence_requester",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="organizationinvitation",
            name="duration_hours",
            field=models.PositiveIntegerField(default=168),
        ),
    ]
